name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        compiler: [gcc, clang]
        crypto: [openssl, gnutls]
        bittorrent: [with-bt, without-bt]
        exclude:
        - os: macos-14
          crypto: gnutls
        - crypto: openssl
          bittorrent: without-bt

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Linux setup
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install \
          g++-12 \
          clang-15 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libgnutls28-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev
    - name: MacOS setup
      if: runner.os == 'macOS'
      run: |
        brew install cppunit gettext openssl@3 libssh2 c-ares sqlite3 \
          autoconf automake pkg-config libtool
        
        # 显示并验证automake版本和位置
        brew info automake
        which automake
        automake --version
        
        # 显示automake辅助文件的位置
        echo "查找automake辅助文件位置："
        find /opt/homebrew/share -name "compile" | grep automake || echo "未找到compile文件"
        find /opt/homebrew/share -name "missing" | grep automake || echo "未找到missing文件"
    - name: Setup clang (Linux)
      if: runner.os == 'Linux' && matrix.compiler == 'clang'
      run: |
        echo 'CC=clang-15' >> $GITHUB_ENV
        echo 'CXX=clang++-15' >> $GITHUB_ENV
    - name: Setup clang (MacOS)
      if: runner.os == 'macOS' && matrix.compiler == 'clang'
      run: |
        echo 'CC=clang' >> $GITHUB_ENV
        echo 'CXX=clang++' >> $GITHUB_ENV
    - name: Setup gcc (Linux)
      if: runner.os == 'Linux' && matrix.compiler == 'gcc'
      run: |
        echo 'CC=gcc-12' >> $GITHUB_ENV
        echo 'CXX=g++-12' >> $GITHUB_ENV
    - name: Setup gcc (MacOS)
      if: runner.os == 'macOS' && matrix.compiler == 'gcc'
      run: |
        echo 'CC=gcc' >> $GITHUB_ENV
        echo 'CXX=g++' >> $GITHUB_ENV

    - name: Prepare build system
      run: |
        # 确保生成所有必要的配置文件
        echo "Running autoreconf..."
        autoreconf -i
        echo "Running automake..."
        automake --add-missing || true
        echo "Running libtoolize..."
        libtoolize --force || glibtoolize --force || true
        echo "Running autopoint..."
        autopoint || echo "autopoint failed, continuing anyway"
        
        # 检查并手动创建缺失的辅助文件
        echo "检查必要的辅助文件..."
        # 检测操作系统类型
        if [ "$RUNNER_OS" == "macOS" ]; then
          # macOS特定路径和命令
          AUTOMAKE_DIRS=(
            "/opt/homebrew/share/automake-*"
            "/usr/local/share/automake-*"
            "/usr/share/automake-*"
          )
        else
          # Linux特定路径
          AUTOMAKE_DIRS=(
            "/usr/share/automake-*"
            "/usr/local/share/automake-*"
          )
        fi
        
        # 通用函数：尝试从系统中找到并复制文件
        copy_automake_file() {
          local file_name=$1
          local found=false
          
          # 检查当前文件是否已存在
          if [ -f "$file_name" ]; then
            echo "$file_name 已存在，无需创建"
            return 0
          fi
          
          echo "尝试查找 $file_name..."
          
          # 从系统目录查找文件
          for dir in "${AUTOMAKE_DIRS[@]}"; do
            if ls $dir/$file_name 1>/dev/null 2>&1; then
              newest_file=$(ls -t $dir/$file_name 2>/dev/null | head -1)
              if [ -n "$newest_file" ]; then
                echo "从 $newest_file 复制 $file_name"
                cp "$newest_file" ./$file_name
                found=true
                break
              fi
            fi
          done
          
          # 如果仍未找到，尝试从网络获取
          if [ "$found" = false ]; then
            echo "未在系统中找到 $file_name，尝试从网络获取..."
            curl -sS -o $file_name "https://raw.githubusercontent.com/autotools-mirror/automake/master/lib/$file_name" && \
            chmod +x $file_name && \
            echo "成功从网络下载 $file_name" || \
            echo "无法获取 $file_name"
          fi
        }
        
        # 复制必要的辅助文件
        copy_automake_file "compile"
        copy_automake_file "missing"
        
        # 显示当前目录中的辅助文件
        echo "查看当前辅助文件："
        ls -l compile missing install-sh config.guess config.sub ltmain.sh 2>/dev/null || echo "部分文件仍然缺失"

    - name: Set compiler flags (Linux)
      if: runner.os == 'Linux'
      run: |
        asanflags="-fsanitize=address,undefined -fno-sanitize-recover=undefined"

        CPPFLAGS="$asanflags -g3"
        LDFLAGS="$asanflags"
        echo 'CPPFLAGS='"$CPPFLAGS" >> $GITHUB_ENV
        echo 'LDFLAGS='"$LDFLAGS" >> $GITHUB_ENV

    - name: Set compiler flags (macOS)
      if: runner.os == 'macOS'
      run: |
        # macOS特定编译标志
        BREW_PREFIX=$(brew --prefix)
        echo "BREW_PREFIX=$BREW_PREFIX"
        
        # 设置OpenSSL路径
        OPENSSL_PATH="$BREW_PREFIX/opt/openssl@3"
        GETTEXT_PATH="$BREW_PREFIX/opt/gettext"
        
        CPPFLAGS="-I$OPENSSL_PATH/include -I$GETTEXT_PATH/include -g3"
        LDFLAGS="-L$OPENSSL_PATH/lib -L$GETTEXT_PATH/lib"
        
        echo 'CPPFLAGS='"$CPPFLAGS" >> $GITHUB_ENV
        echo 'LDFLAGS='"$LDFLAGS" >> $GITHUB_ENV
    - name: Disable BitTorrent
      if: matrix.bittorrent == 'without-bt'
      run: |
        FEATURE_FLAGS="$FEATURE_FLAGS --disable-bittorrent"

        echo 'FEATURE_FLAGS='"$FEATURE_FLAGS" >> $GITHUB_ENV
    - name: Configure autotools (Linux, gnutls)
      if: runner.os == 'Linux' && matrix.crypto == 'gnutls'
      run: |
        ./configure --with-gnutls --without-openssl $FEATURE_FLAGS || { cat config.log; exit 1; }
        # 验证config.status已创建在正确位置
        ls -la config.status

    - name: Configure autotools (Linux, openssl)
      if: runner.os == 'Linux' && matrix.crypto == 'openssl'
      run: |
        ./configure --without-gnutls --with-openssl $FEATURE_FLAGS || { cat config.log; exit 1; }
        # 验证config.status已创建在正确位置
        ls -la config.status

    - name: Configure autotools (macOS)
      if: runner.os == 'macOS'
      run: |
        # 再次确认辅助文件存在
        echo "确保auxdir辅助文件存在..."
        if [ ! -f "compile" ] || [ ! -f "missing" ]; then
          echo "缺少辅助文件，重新创建..."
          automake --add-missing --copy
          
          # 如果仍然缺失，手动从系统复制
          if [ ! -f "compile" ]; then
            AUTOMAKE_DIR=$(ls -d /opt/homebrew/Cellar/automake/*/share/automake-* | head -1)
            echo "从 $AUTOMAKE_DIR 复制compile文件"
            cp "$AUTOMAKE_DIR/compile" ./
          fi
          
          if [ ! -f "missing" ]; then
            AUTOMAKE_DIR=$(ls -d /opt/homebrew/Cellar/automake/*/share/automake-* | head -1)
            echo "从 $AUTOMAKE_DIR 复制missing文件"
            cp "$AUTOMAKE_DIR/missing" ./
          fi
        fi
        
        # 确保目录中存在这些文件
        ls -la compile missing
        
        # 配置构建
        ./configure \
          --without-openssl --without-gnutls --with-appletls \
          --disable-nls || { cat config.log; exit 1; }
        # 验证config.status已创建在正确位置
        ls -la config.status

    - name: Fix config.status path issues
      run: |
        # 检查po/Makefile.in.in文件中的config.status路径引用
        if [ -f po/Makefile.in.in ]; then
          echo "检查并修复po/Makefile.in.in中的config.status路径..."
          
          if [ "$RUNNER_OS" == "Linux" ]; then
            # Linux版本sed命令
            sed -i 's|\./config.status|../config.status|g' po/Makefile.in.in
          else
            # macOS版本sed命令
            sed -i '' 's|\./config.status|../config.status|g' po/Makefile.in.in
          fi
          
          echo "创建config.status符号链接到根目录..."
          # 创建指向实际config.status的符号链接
          ln -sf $(pwd)/config.status /config.status 2>/dev/null || true
          
          # 备份方案：如果符号链接失败，尝试创建一个最小的config.status文件
          if [ ! -f /config.status ]; then
            echo "符号链接创建失败，创建临时的config.status文件..."
            echo "#!/bin/sh" | sudo tee /config.status > /dev/null
            sudo chmod +x /config.status
          fi
        else
          echo "po/Makefile.in.in不存在，跳过修复步骤"
        fi
        
        # 显示当前工作目录和关键文件
        pwd
        ls -la config.status || echo "config.status not found"
        ls -la po/Makefile.in.in || echo "po/Makefile.in.in not found"

    - name: Build aria2
      run: |
        # 尝试构建，如果失败也要继续执行工作流
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" || echo "Build failed but continuing"
        
    - name: Run tests
      run: |
        # 运行测试，保存返回状态
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check || echo "Tests failed with status $?"
        
    - name: Create artifacts directory
      if: always()
      run: |
        mkdir -p artifacts
        cp -f src/aria2c artifacts/ 2>/dev/null || echo "aria2c binary not found"
        cp -f config.log artifacts/ 2>/dev/null || echo "config.log not found"
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: aria2-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.crypto }}
        path: artifacts/
        retention-days: 7
